version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "status-board"
s3_prefix = "status-board"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "SiteName=\"Some Site\""
